name: SGM
version: '${version}'
main: SGM.SGM.SGM
api-version: 1.13
author: CraftSupport
commands:
  god:
    description: Command to Enable And Disable GodMode
    usage: /<command>
    permission: SGM.godmode
    permission-message: "&4&l U do not have permission for this command"