name: Tesada
version: '${version}'
main: tesada.tesada.Tesada
api-version: 1.19
author: CraftSupport
commands:
  god:
    description: Command to Enable And Disable GodMode
    usage: /<command>
    permission: tesada.godmode