name: SGM
version: '${version}'
main: sgm.sgm.SGM
api-version: 1.13
author: CraftSupport
commands:
  god:
    description: Command to Enable And Disable GodMode
    usage: /<command>
    permission: SGM.godmode